name: Slack Tot Bot

on:
  schedule:
    - cron: "0 9 * * 1-5" # Runs at 9 AM Monday to Friday
  workflow_dispatch:

jobs:
  tots-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run bot
        env:
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          NODE_ENV: ${{ vars.NODE_ENV }}
        run: node bot.js
